Fix issues with gsettings test command. Always need to copy the schema file to binary dir.

diff --git a/debian/tests/gsettings b/debian/tests/gsettings
--- a/debian/tests/gsettings
+++ b/debian/tests/gsettings
@@ -8,7 +8,7 @@ set -euo pipefail
 IFS=$'\n\t'
 
 tempdir=$(mktemp --tmpdir="${AUTOPKGTEST_TMP:-/tmp}" -d)
-trap "rm -rf $tempdir" 0 INT QUIT ABRT PIPE TERM
+#trap "rm -rf $tempdir" 0 INT QUIT ABRT PIPE TERM
 
 demodir="$(pwd)/examples/gsettings-demo"
 srcdir="${tempdir}/source"
@@ -32,9 +32,14 @@ DEFAULT_UUID=$(uuidgen)
 ### Test the schemas
 check_schema() {
     VALUE=$(gsettings get $1 $2)
-    EXPECTED=$3
+    EXPECTED=${3:-0}
 
-    if [ "${VALUE}" != "${EXPECTED}" ]; then
+    echo -n "/schema/$1/$2: "
+
+    if [ "${VALUE}" == "${EXPECTED}" ]; then
+        echo "OK"
+    else
+        echo "FAILED"
         echo "Generated schema is wrong."
         echo "\tActual:   ${VALUE}"
         echo "\tExpected: ${EXPECTED}"
@@ -44,10 +49,10 @@ check_schema() {
 
 # Verify the built schemas
 export GSETTINGS_SCHEMA_DIR="${bindir}"
-check_schema(com.canonical.cmake-extras.generated-test install-id "'${DEFAULT_UUID}'")
-check_schema(gsettings get com.canonical.cmake-extras.static-test use-gsettings false)
+check_schema "com.canonical.cmake-extras.generated-test" "install-id" "'${DEFAULT_UUID}'"
+check_schema "com.canonical.cmake-extras.static-test" "use-gsettings" "false"
 
 # Verify the installed schemas
 export GSETTINGS_SCHEMA_DIR="${installdir}/share/glib-2.0/schemas"
-check_schema(com.canonical.cmake-extras.generated-test install-id "'${DEFAULT_UUID}'")
-check_schema(gsettings get com.canonical.cmake-extras.static-test use-gsettings false)
+check_schema "com.canonical.cmake-extras.generated-test" "install-id" "'${DEFAULT_UUID}'"
+check_schema "com.canonical.cmake-extras.static-test" "use-gsettings" "false"
